### ISSUE TITLE
New Ideas for projects and website features

### ISSUE THREAD

**Issue by srichakradhar** [fcc-hyd/fcc-hyd.github.io#29]
Post any ideas you have for community projects or features for [our website](https://fcc-hyd.github.io/). If others think it's a good idea and we should go ahead, we'll create a separate issue to discuss it and start planning. You can vote by giving a thumbs up

**Comment by keshavnarla** [comment]
I would like to see my pic and a link to my profile!

**Comment by duttakapil** [comment]
- Member profiles
- Schedule
- Connected companies 
- Job postings
- Meetup timer
- Our philosophy
- Leaderboard 
- Our open source projects section
- Guide (how to pair program virtually/physically, how to update profile/contribute to projects, intro to topics for absolute beginners etc)

**Comment by duttakapil** [comment]
We should build an "Intro to JavaScript" teaching tool, just like our [Into to HTML/CSS project](https://fcc-hyd.github.io/projects/intro-to-html-css). I imagine it to look something like [JavaScript.com](https://www.javascript.com/) or [Learn-JS](http://www.learn-js.org/). The purpose is to give a quick intro to JavaScript to absolute beginners at our meetups, so that they can start practicing by solving coding challenges as soon as possible.

**Comment by srichakradhar** [comment]
Create a pair programming solution for our community, similar to: http://www.codermatch.me/users/srichakradhar or http://letspair.net/

**Comment by anushreddy** [comment]
This pair programming session is a good thought.

**Comment by nishantmadu** [comment]
We should have 5 new coding challenges in JS everyday and a leaderboard along with it.

**Comment by nishantmadu** [comment]
A new app challenge should be introduced.In which a best idea proposed by FCC community shall be taken and members need to complete in the app in a week's time.A countdown will be running in the website.

**Comment by Raghuram42** [comment]
Hey guys,
My idea is to build Face Recognition & Voice Recognition through Machine Learning in Python.
