### ISSUE TITLE
Change font style and letter spacing for issues page

### ISSUE THREAD

**Issue by duttakapil** [fcc-hyd/fcc-hyd.github.io#49]
@vramana has suggested that we should change the font style and the letter spacing for the [issues page](https://fcc-hyd.github.io/issues/)

![image](https://cloud.githubusercontent.com/assets/6577624/20928428/ce3b67fe-bbeb-11e6-81eb-dbb36a86da64.png)

**Comment by vinaypuppal** [comment]
![whatsapp image 2016-12-06 at 8 04 01 pm](https://cloud.githubusercontent.com/assets/8843216/20929579/9a882f0a-bbf0-11e6-857c-c8cdae1a5f54.jpeg)

I think @vramana is talking about irregular spacing between words, it is caused due to `text-align: justify` at  [these lines in css](https://github.com/fcc-hyd/fcc-hyd.github.io/blob/1b40f37eed1085398a7b3027f735a136328cb4cb/issues/css/index.css#L257-L260)

### For anyone who want contribute to this issue
- So no need of changing letter-spacing, just need to write a media query for mobile screen sizes and change text-align to left would solve that.
- For fonts you can pick font-family from main fcc-hyd repo https://github.com/fcc-hyd/fcc-hyd.github.io/blob/master/styles/main.css#L6-L17

**Comment by Fransenson** [comment]
Hey! I just did this - am I allowed to submit a pull request?
