### ISSUE TITLE
Single Page App??

### ISSUE THREAD

**Issue by JinnaBalu** [fcc-hyd/fcc-hyd.github.io#53]
if yes, I create the app, we need to rewrite the app. As our app is in initial stage so we can create rewrite very easily.

**Comment by duttakapil** [comment]
@JinnaBalu the code is structured the way it is because we're using gh-pages for hosting. We need index.html in every folder, to display the contents on our website.

**Comment by duttakapil** [comment]
@JinnaBalu you will have to send another Pull Request to add your profile to the Members List. The last one you sent was not done properly. You did not edit your profile summary and page correctly, and made some unnecessary changes.

**Comment by vramana** [comment]
Adding index.html is for every member is very tedious process. If somebody wants to change the member layout, They have to go change all the index.html. We can just render each member's profile using JSON.

Angular feels like an overkill. I would prefer to keep this website as close to vanilla JS as possible. We can use a little router library so that we have url for each page.

**Comment by duttakapil** [comment]
@vramana we have actually been planning to switch to using JSON. We were also planning to  build a bot, like the one J Lord uses for her Patchwork repo, to handle the pull-requests

**Comment by JinnaBalu** [comment]
can I create an angular js/typescript app with json with bootstrap, scafolding is not so good of our existing app. Let me know if you want me to continue.
